#! /bin/sh

# Runs `create-project-launch-config` script for all projects

projects=$($(dirname $0)/list-gh-repos)

for project in $projects; do
    $(dirname $0)/create-project-launch-config "$project"
done
